credentials:
  usernames:
    irma:
      email: irmakaleem12@gmail.com
      logged_in: False # Will be managed automatically
      name: irma kaleem
      password: abc # Will be hashed automatically
    omer:
      email: omerfarooqkhan7210@gmail.com
      logged_in: False # Will be managed automatically
      name: omer khan
      password: def # Will be hashed automatically
cookie:
  expiry_days: 30
  key: some_signature_key # Must be string
  name: some_cookie_name
preauthorized:
  emails:
  - melsby@gmail.com